name: WIN Matrix

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2025]

    steps:
      - uses: actions/checkout@v4 

      - name: Runner 
        shell: powershell
        run: .\Actions\workflow_windows11_24H2.ps1

      - name: Artifact
        #if: success() 
        uses: actions/upload-artifact@v4
        with:
          name: ArtifactName1
          path: PhysX50.zip  

